### PR TITLE
Add ask method for NewMessage

### PR DESCRIPTION
**Pull request by jonneyless**
example:

```
client.AddMessageHandler(telegram.OnNewMessage, func(message *telegram.NewMessage) error {
	answer, err := message.Ask("Input your name.")
	if err != nil {
		return err
	}
	
	_, err = answer.Reply("Got your name!")
	if err != nil {
		return err
	}
	
	return nil
})
```

### CODE REVIEW

**Comment by AmarnathCJD** [comment]
https://github.com/AmarnathCJD/gogram/blob/2754b67746caef705c5476d025450bdec87966cc/telegram/conversation.go#L23

wouldn't this type impl be better.?

**Comment by jonneyless** [comment]
> https://github.com/AmarnathCJD/gogram/blob/2754b67746caef705c5476d025450bdec87966cc/telegram/conversation.go#L23
> 
> wouldn't this type impl be better.?

Oh, So there's this type. I try it.

```
talk, err := b.client.NewConversation(message.SenderID(), true)
if err != nil {
	return err
}
_, err = talk.SendMessage("Input your username.")
if err != nil {
	return err
}
reply, err := talk.GetResponse()
if err != nil {
	return err
}
_, _ = reply.Reply("Got your username.")
```

This is the feature I want.

**Comment by jonneyless** [comment]
More complete documentation is required

**Comment by AmarnathCJD** [comment]
Mhm, also I'll add short handle .Ask for this, nice idea

**Pull request closed without merging**
