### PR TITLE
refactor download media

### PR DESCRIPTION
**Pull request by eos175**

### CODE REVIEW

**Comment by AmarnathCJD** [comment]
Nope

**Comment by AmarnathCJD** [comment]
Not handling timeouts; It would stuck occasionally 

See the current impl timeouts

**Comment by eos175** [comment]
The `FLOOD_WAIT`?

**Comment by AmarnathCJD** [comment]
> The `FLOOD_WAIT`?

Nope,  sometimes a UploadGetFile req timeouts and takes long to retu6which caused the block at wg.Wait(), I fixed it by adding timeouts and retry.

**Comment by AmarnathCJD** [comment]
> > The `FLOOD_WAIT`?
> 
> Nope, sometimes a UploadGetFile req timeouts and takes long to retu6which caused the block at wg.Wait(), I fixed it by adding timeouts and retry.

Probably due to TCp getting flooded with reqs.

**Comment by eos175** [comment]
Uploads don't have a `timeout`; don't they have this issue?

My bots don't download very large files, but I'll check it

**Comment by AmarnathCJD** [comment]
Haven't spotted this in uploads yet.

**Comment by AmarnathCJD** [comment]
??

**Comment by eos175** [comment]
For now, I'm going to close it. I'll fix it over the weekend

**Pull request closed without merging**
