### PR TITLE
best fileID, support legacy

### PR DESCRIPTION
**Pull request by eos175**

### CODE REVIEW

**Comment by RoseLoverX** [comment]
@eos175 why removed rlc and that xor?

**Comment by eos175** [comment]
That's something I was experimenting with. In my case, `DC=1`, so I applied `xor=1`, which reduces the size to 26 bytes in b64. The problem is that everyone has different DC values. At the end of my tests, it's not worth applying a corrector and RLC to reduce 3 bytes, yes, 3 bytes, because you have to store the predictor that was used

**Comment by eos175** [comment]
You can leave only RLC_Zero, but honestly, I don't think it's worth it for just 2 bytes in most cases. If you want to reduce more, you should use another base, but that adds dependencies to the project. Simply encoding in binary is sufficient

**Comment by RoseLoverX** [comment]
but u said dc1, mine's dc5 and that fn seems to work?

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by eos175** [comment]
You are only using RLC. Change 1 -> 5 and there will be more zeros, resulting in something even smaller.

```go
return base64.RawURLEncoding.EncodeToString(RLCEncode(applyXORInt32(buf, 0x00000005)))
```

**Comment by eos175** [comment]
The known types fit well within 1 byte, as do the DC values [1-5].

Would it be better to use 3 bytes for the types and 1 byte for the DC?

With `fileType [3] | dcID [1]`, the length would be 27 bytes.

With `fileType [1] | dcID [1]`, the length is 24 bytes.

I think this is better than RLC

**Comment by eos175** [comment]
I consider that 3 bytes for the type is better, as it provides some margin

```go
func PackBotFileID(file any) string {
	...

	buf := make([]byte, 4+8+8)
	binary.LittleEndian.PutUint32(buf[0:], uint32(fileType)|uint32(dcID)<<24)
	binary.LittleEndian.PutUint64(buf[4:], uint64(fID))
	binary.LittleEndian.PutUint64(buf[4+8:], uint64(accessHash))
	return base64.RawURLEncoding.EncodeToString(buf)
}

func UnpackBotFileID(fileID string) (int64, int64, int32, int32) {
	...
	if len(data) == 20 {
		tmp := binary.LittleEndian.Uint32(data[0:])
		fileType := int32(tmp & 0x00FFFFFF)
		dcID := int32((tmp >> 24) & 0xFF)
		fID := int64(binary.LittleEndian.Uint64(data[4:]))
		accessHash := int64(binary.LittleEndian.Uint64(data[4+8:]))
		return fID, accessHash, fileType, dcID
	}
	...
}
```

**Pull request closed without merging**
