### PR TITLE
Update react.go

### PR DESCRIPTION
**Pull request by MukundSinghRajput**
fixed typo

### CODE REVIEW

**Comment by TAMILVIP007** [comment]
@MukundSinghRajput go away

**Comment by MukundSinghRajput** [comment]
@TAMILVIP007 ?

**Comment by TAMILVIP007** [comment]
@MukundSinghRajput hurr

**Comment by AnjanaMadu** [comment]
@TAMILVIP007 ur not suppose to fix typos of cdj. he is the supreme here 🤡

**Comment by AnjanaMadu** [comment]
@TAMILVIP007 yes  u

**Comment by TAMILVIP007** [comment]
@AnjanaMadu nou

**Comment by AnjanaMadu** [comment]
@TAMILVIP007 yes @MukundSRajput he is

**Comment by TAMILVIP007** [comment]
@AnjanaMadu no @spechide he is

**Comment by MukundSinghRajput** [comment]
You all are gays

**Pull request merged**
