### PR TITLE
Refactor Error Handling: Replace `github.com/pkg/errors` with `fmt.Errorf` 

### PR DESCRIPTION
**Pull request by AshokShau**
Refactors error handling by replacing `github.com/pkg/errors` with Go's native `fmt.Errorf` for error wrapping. This reduces dependencies and improves code consistency.

Changes include:
- Replaced `errors.Wrap` and `errors.New` with `fmt.Errorf` using `%w`.
- Removed `github.com/pkg/errors` from `go.mod` and `go.sum`.
- Rebasing changes on the latest `master` from upstream.  ( I hope force push works)

### CODE REVIEW

**Comment by RoseLoverX** [comment]
@AshokShau Ah

**Comment by AmarnathCJD** [comment]
what about stack traces :)

**Comment by AshokShau** [comment]
> what about stack traces :)

you can use the `errors` package for error wrapping with stack trace support.

**Comment by TAMILVIP007** [comment]
@AshokShau your commit literally removes that pkg

**Comment by TAMILVIP007** [comment]
@AmarnathCJD

**Comment by TAMILVIP007** [comment]
@AmarnathCJD

**Comment by TAMILVIP007** [comment]
@AmarnathCJD

**Comment by TAMILVIP007** [comment]
@AmarnathCJD

**Comment by TAMILVIP007** [comment]
@AmarnathCJD

**Comment by TAMILVIP007** [comment]
@AmarnathCJD

**Comment by AshokShau** [comment]
> your commit literally removes that pkg

you can use runtime/debug but whare you using ? in this repo

**Comment by AmarnathCJD** [comment]
Ah lemme test it out.

**Comment by AmarnathCJD** [comment]
not planned;

**Comment by AmarnathCJD** [comment]
focusing on real implimentation probelms, if any, currenly not accepting code beautifications, it would just mess up more;)

**Comment by AshokShau** [comment]
> focusing on real implimentation probelms, if any, currenly not accepting code beautifications, it would just mess up more;)

lol: ;) - "This wasn't about beautification—it aimed to reduce dependencies, but got it, I'll focus on core issues!"

**Pull request closed without merging**
